---
- name: Download ussher binary
  ansible.builtin.get_url:
    url: "{{ ussher_binary_url }}"
    dest: "{{ ussher_binary_path }}"
    mode: 0750

- name: Create ussher group
  ansible.builtin.group:
    name: "{{ ussher_user }}"
    system: true

- name: Create ussher user
  ansible.builtin.user:
    name: "{{ ussher_user }}"
    shell: "/usr/sbin/nologin"
    group: "{{ ussher_user }}"
    system: true

- name: Create ussher config directory
  ansible.builtin.file:
    path: "{{ ussher_config_dir }}"
    state: directory

- name: Create ussher cache directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ ussher_cache_dir }}"
    state: directory
    mode: 0700
    owner: "{{ ussher_user }}"
    group: "{{ ussher_user }}"
    setype: sshd_t

- name: Create ussher log directory
  ansible.builtin.file:
    path: "{{ ussher_log_dir }}"
    state: directory
    mode: 0700
    owner: "{{ ussher_user }}"
    group: "{{ ussher_user }}"
    setype: sshd_t

- name: Update sshd configuration
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#?AuthorizedKeysCommand .*"
    line: "AuthorizedKeysCommand {{ ussher_binary_path }}"
  notify: Restart sshd

- name: Update sshd configuration
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#?AuthorizedKeysCommandUser .*"
    line: "AuthorizedKeysCommandUser {{ ussher_user }}"
  notify: Restart sshd

- name: Validate sshd configuration
  ansible.builtin.command: "sshd -t"
  changed_when: false

- name: Configure selinux
  ansible.builtin.import_tasks: selinux.yml
  tags: selinux
