---
- name: Download ussher binary
  become: true
  ansible.builtin.get_url:
    url: "{{ ussher_binary_url }}"
    dest: "{{ ussher_binary_path }}"
    mode: 0750

- name: Create ussher group
  become: true
  ansible.builtin.group:
    name: "{{ ussher_user }}"
    system: true

- name: Create ussher user
  become: true
  ansible.builtin.user:
    name: "{{ ussher_user }}"
    shell: "/usr/sbin/nologin"
    group: "{{ ussher_user }}"
    system: true

- name: Create ussher config directory
  become: true
  ansible.builtin.file:
    path: "{{ ussher_config_dir }}"
    state: directory

- name: Create ussher cache directory
  become: true
  ansible.builtin.file:
    path: "{{ ussher_cache_dir }}"
    state: directory
    mode: 0700
    owner: "{{ ussher_user }}"
    group: "{{ ussher_user }}"

- name: Create ussher log directory
  become: true
  ansible.builtin.file:
    path: "{{ ussher_log_dir }}"
    state: directory
    mode: 0700
    owner: "{{ ussher_user }}"
    group: "{{ ussher_user }}"

- name: Update sshd configuration
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#?AuthorizedKeysCommand .*"
    line: "AuthorizedKeysCommand {{ ussher_binary_path }}"
  notify: Restart sshd

- name: Update sshd configuration
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#?AuthorizedKeysCommandUser .*"
    line: "AuthorizedKeysCommandUser {{ ussher_user }}"
  notify: Restart sshd

- name: Validate sshd configuration
  become: true
  ansible.builtin.command: "sshd -t"
  changed_when: false

- name: Push selinux type enforcement file
  ansible.builtin.copy:
    src: ussher.te
    dest: /tmp/ussher.te
    owner: root
    group: root
    mode: 0644

- name: Push policy module
  become: true
  copy:

- name: Compile policy module
  become: true
  ansible.builtin.command:
    cmd: checkmodule -M -m -o /tmp/ussher.mod /tmp/ussher.te

- name: Create an installable policy file from the policy module
  become: true
  ansible.builtin.command:
    cmd: semodule_package -o /tmp/ussher.pp -m /tmp/ussher.mod

- name: Install ussher's policy file
  become: true
  ansible.builtin.command:
    cmd: semodule_package -o /tmp/ussher.pp -m /tmp/ussher.mod

- name: Check if ussher module is already installed
  ansible.builtin.shell: semodule -l | grep -w ussher
  register: ussher_module_installed
  failed_when: false
  changed_when: false
  become: true

- name: Install ussher.pp SELinux policy package
  ansible.builtin.shell: semodule -i /tmp/ussher.pp
  when: ussher_module_installed.rc != 0
  become: true
